### PR TITLE
Update CONTRIBUTING.md with CNCF CLAs

### PR DESCRIPTION
**Pull request by mbohlool**
I assume we need CNCF CLAs now that we are part of CNCF. Please double-check the links and the text. I am not sure what is the official/legal way to represent this.

### CODE REVIEW

**Review by sarahnovotny — CHANGES_REQUESTED** [review]
there is no need to become a member of the CNCF or the LF to contribute code.  you or your company only need to sign the [C]CLA.

**Comment by mbohlool** [comment]
I didn't find a link for the company to sign CLA. Two links above was for signing CLA as employee (not employer) or individual. 
Am I correct that we need to update this file or signing Google CLA works too?

**Comment by sarahnovotny** [comment]
the company signup url is https://identity.linuxfoundation.org/node/285/organization-signup.

There should be no references to the Google [C]CLAs.  And no need for the contributors or contributing organization to become a member of the LF or the CNCF.

Thanks for catching this and updating it!  cc/@foxish

**Comment by mbohlool** [comment]
OK, I've only updated the links (no text changes).

**Review by sarahnovotny — APPROVED** [review]

**Pull request merged**
