### PR TITLE
OWNERS: Upstream docs moved from devel/ to guide/

### PR DESCRIPTION
**Pull request by wking**
Catch up with kubernetes/community#1764.

### CODE REVIEW

**Comment by wking** [comment]
Anything I can do to help this along?  The links currently in master are 404ing.

**Comment by wking** [comment]
@spiffxp, anything I can do to help this along?  @cblecker LGTMed this back in May, and it would be nice to have a working link ;).

**Comment by spiffxp** [comment]
/approve
sorry for the delay, I've been out for a while, thanks for the fix

**Pull request merged**
