### PR TITLE
Change code-of-conduct to call by reference

### PR DESCRIPTION
**Pull request by dankohn**
This matches what kubernetes/kubernetes has.

### CODE REVIEW

**Comment by spiffxp** [comment]
I would rather we link to https://github.com/kubernetes/community/blob/master/code-of-conduct.md, which already calls up to the CNCF code of conduct.  I'm waiting to hear feedback from other members of the steering committee.

**Comment by dankohn** [comment]
LGTM

**Review by timothysc — APPROVED** [review]
/lgtm

**Comment by spiffxp** [comment]
/hold
holding to use this as a guinea pig for tide, but like I said, I'd rather link to community as another level of indirection

**Pull request merged**
